function mustGet<T extends Element>(selector: string): T {
  const node = document.querySelector<T>(selector);
  if (!node) {
    throw new Error(`Viewer element missing: ${selector}`);
  }
  return node;
}

export const dom = {
  viewer: mustGet<HTMLElement>(".viewer"),
  fileName: mustGet<HTMLSpanElement>("#fileName"),
  fileSize: mustGet<HTMLSpanElement>("#fileSize"),
  themeToggle: mustGet<HTMLButtonElement>("#themeToggle"),
  openAnother: mustGet<HTMLButtonElement>("#openAnother"),
  fit: mustGet<HTMLButtonElement>("#fit"),
  fitAll: mustGet<HTMLButtonElement>("#fitAll"),
  sidebarToggle: mustGet<HTMLButtonElement>("#sidebarToggle"),
  layers: mustGet<HTMLUListElement>("#layers"),
  layersEmpty: mustGet<HTMLParagraphElement>("#layersEmpty"),
  layerSearch: mustGet<HTMLInputElement>("#layerSearch"),
  canvasHost: mustGet<HTMLDivElement>("#canvasHost"),
  dropOverlay: mustGet<HTMLDivElement>("#dropOverlay"),
  overlay: mustGet<HTMLDivElement>("#overlay"),
  overlayText: mustGet<HTMLParagraphElement>("#overlayText"),
  overlaySpinner: mustGet<HTMLDivElement>("#overlaySpinner"),
  overlayAction: mustGet<HTMLButtonElement>("#overlayAction"),
  fileInput: mustGet<HTMLInputElement>("#fileInput"),
  content: mustGet<HTMLElement>(".content"),
  coordReadout: mustGet<HTMLDivElement>("#coordReadout"),
  coordX: mustGet<HTMLSpanElement>("#coordX"),
  coordY: mustGet<HTMLSpanElement>("#coordY"),
  recentToggle: mustGet<HTMLButtonElement>("#recentToggle"),
  recentMenu: mustGet<HTMLDivElement>("#recentMenu"),
  recentList: mustGet<HTMLUListElement>("#recentList"),
  recentEmpty: mustGet<HTMLParagraphElement>("#recentEmpty"),
  measureToggle: mustGet<HTMLButtonElement>("#measureToggle"),
  measureOverlay: mustGet<HTMLDivElement>("#measureOverlay"),
  findToggle: mustGet<HTMLButtonElement>("#findToggle"),
  languageToggle: mustGet<HTMLButtonElement>("#languageToggle"),
  languageMenu: mustGet<HTMLDivElement>("#languageMenu"),
  languageSearch: mustGet<HTMLInputElement>("#languageSearch"),
  languageList: mustGet<HTMLUListElement>("#languageList"),
  findBar: mustGet<HTMLDivElement>("#findBar"),
  findInput: mustGet<HTMLInputElement>("#findInput"),
  findCount: mustGet<HTMLSpanElement>("#findCount"),
  findPrev: mustGet<HTMLButtonElement>("#findPrev"),
  findNext: mustGet<HTMLButtonElement>("#findNext"),
  findClose: mustGet<HTMLButtonElement>("#findClose"),
  printBtn: mustGet<HTMLButtonElement>("#printBtn"),
  screenshotBtn: mustGet<HTMLButtonElement>("#screenshotBtn"),
  minimapToggle: mustGet<HTMLButtonElement>("#minimapToggle"),
  coordsToggle: mustGet<HTMLButtonElement>("#coordsToggle"),
  colorModeToggle: mustGet<HTMLButtonElement>("#colorModeToggle"),
  toast: mustGet<HTMLDivElement>("#toast"),
  bookmarksList: mustGet<HTMLUListElement>("#bookmarksList"),
  bookmarksEmpty: mustGet<HTMLParagraphElement>("#bookmarksEmpty"),
  bookmarkAdd: mustGet<HTMLButtonElement>("#bookmarkAdd"),
  compareBar: mustGet<HTMLDivElement>("#compareBar"),
  compareLabel: mustGet<HTMLSpanElement>("#compareLabel"),
  compareBaseToggle: mustGet<HTMLButtonElement>("#compareBaseToggle"),
  compareLayerToggle: mustGet<HTMLButtonElement>("#compareLayerToggle"),
  compareBaseIcon: mustGet<HTMLSpanElement>("#compareBaseIcon"),
  compareLayerIcon: mustGet<HTMLSpanElement>("#compareLayerIcon"),
  compareOpacity: mustGet<HTMLInputElement>("#compareOpacity"),
  compareExit: mustGet<HTMLButtonElement>("#compareExit"),
  snapMarker: mustGet<HTMLDivElement>("#snapMarker"),
  minimapCanvas: mustGet<HTMLCanvasElement>("#minimapCanvas"),
  entityTooltip: mustGet<HTMLDivElement>("#entityTooltip"),
} as const;
